PHPCommerce\Payment\Entity\OrderPayment:
  type: entity
  table: order_payment

  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    type:
      type: payment_type
      length: 255
      column: type

    gatewayType:
      type: payment_gateway_type
      type: string
      length: 255
      column: gateway_type

    referenceNumber:
      type: string
      length: 255
      column: reference_number

  oneToMany:
    transactions:
      targetEntity: PHPCommerce\Payment\Entity\PaymentTransaction
      mappedBy: order_payment
      cascade:
        - persist

  manyToOne:
    order:
      targetEntity: PHPCommerce\ERP\Entity\Order
      inversedBy: payments
      cascade:
        - persist
      joinColumn:
        name: order_id
        referencedColumnName: id
        nullable: false
