PHPCommerce\Payment\Entity\OrderPayment:
  type: entity
  table: order_payment

  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    type:
      type: payment_type
      type: string
      length: 255

  manyToOne:
    order:
      targetEntity: PHPCommerce\ERP\Entity\Order
      inversedBy: payments
      joinColumn:
        name: order_id
        referencedColumnName: id
        nullable: false