PHPCommerce\Payment\Entity\PaymentTransaction:
  type: entity
  table: payment_transaction

  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    type:
      type: payment_transaction_type
      type: string
      length: 255
      nullable: false

    date:
      type: datetime
      column: date
      nullable: false

    customer_ip_address:
      type: string
      column: customer_ip_address
      nullable: false

  manyToOne:
    parent_transaction:
      targetEntity: PHPCommerce\Payment\Entity\PaymentTransaction
      joinColumn:
        name: parent_transaction
        referencedColumnName: id

    payment:
      targetEntity: PHPCommerce\Payment\Entity\Payment
      inversedBy: transactions
      cascade:
        - persist
      joinColumn:
        name: order_payment
        referencedColumnName: id
