PHPCommerce\Payment\Entity\Payment:
  type: entity
  table: payment

  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    type:
      type: payment_type
      length: 255
      column: type

    gatewayType:
      type: payment_gateway_type
      type: string
      length: 255
      column: gateway_type

    reference:
      type: string
      length: 255
      column: reference
      nullable: true

  oneToMany:
    transactions:
      targetEntity: PHPCommerce\Payment\Entity\PaymentTransaction
      mappedBy: order_payment
      cascade:
        - persist

#  manyToOne:
#    order:
#      targetEntity: PHPCommerce\ERP\Entity\Order
#      inversedBy: payments
#      cascade:
#        - persist
#      joinColumn:
#        name: order_id
#        referencedColumnName: id
#        nullable: false

  manyToMany:
    order:
      targetEntity: PHPCommerce\ERP\Entity\Order
      joinTable:
        name: payment_order
        joinColumns:
          payment_id:
            referencedColumnName: id
        inverseJoinColumns:
          order_id:
            referencesColumnName: id
