PHPCommerce\ERP\Entity\Order:
  type: entity
  table: `order`

  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  manyToMany:
    payments:
      targetEntity: PHPCommerce\Payment\Entity\Payment
      cascade:
        - persist
      inversedBy: orders
      joinTable:
        name: order_payment
        joinColumns:
          order_id:
            referencesColumnName: id
        inverseJoinColumns:
          payment_id:
            referencedColumnName: id


