PHPCommerce\ERP\Entity\Order:
  type: entity
  table: `order`

  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  oneToMany:
    payments:
      targetEntity: PHPCommerce\Payment\Entity\OrderPayment
      mappedBy: order