PHPCommerce\Common\Entity\Currency:
  type: entity
  table: currency

  id:
    code:
      type: string
      length: 3
      column: code

  fields:
    name:
      type: string
      length: 255
      column: name

    symbol:
      type: string
      length: 1
      column: symbol

    default:
      type: boolean
      column: default
