doctrine:
  orm:
    entity_managers:
      default:
        mappings:
          ERP:
            mapping: true
            type: yml
            dir: %php_commerce.root_dir%/src/PHPCommerce/ERP/Resources/config/doctrine
            is_bundle: false
            prefix: PHPCommerce\ERP\Entity
