doctrine:
  orm:
    entity_managers:
      default:
        mappings:
          ERP:
            mapping: true
            type: annotation
            dir: %php_commerce.root_dir%/src/PHPCommerce/ERP/Entity
            is_bundle: false
            prefix: PHPCommerce\ERP\Entity
