doctrine:
  dbal:
    types:
        pc_payment_type:          PHPCommerce\Payment\Type\DBAL\PaymentDBALType
        pc_payment_gateway_type:  PHPCommerce\Payment\Type\DBAL\PaymentGatewayDBALType
        pc_payment_gateway_type:  PHPCommerce\Payment\Type\DBAL\PaymentTransactionDBALType

  orm:
    entity_managers:
      default:
        mappings:
          Payment:
            mapping: true
            type: annotation
            dir: %php_commerce.root_dir%/src/PHPCommerce/Payment/Entity
            is_bundle: false
            prefix: PHPCommerce\Payment\Entity
