doctrine:
  orm:
    entity_managers:
      default:
        mappings:
          Payment:
            mapping: true
            type: annotation
            dir: %php_commerce.root_dir%/src/PHPCommerce/Payment/Entity
            is_bundle: false
            prefix: PHPCommerce\Payment\Entity
