doctrine:
  orm:
    entity_managers:
      default:
        mappings:
          Payment:
            mapping: true
            type: yml
            dir: %php_commerce.root_dir%/src/PHPCommerce/Payment/Resources/config/doctrine
            is_bundle: false
            prefix: PHPCommerce\Payment\Entity
