doctrine:
  dbal:
    driver:   %php_commerce.database.driver%
    host:     %php_commerce.database.host%
    port:     %php_commerce.database.port%
    dbname:   %php_commerce.database.name%
    user:     %php_commerce.database.user%
    password: %php_commerce.database.password%
    path:     %php_commerce.database.path%
    server_version: %php_commerce.database.server_version%

    charset:  UTF8

    # if using pdo_sqlite as your database driver:
    #   1. add the path in parameters.yml
    #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
    #   2. Uncomment database_path in parameters.yml.dist
    #   3. Uncomment next line:
    #     path:     "%database_path%"