#framework:
#    templating:
#        engines: ['twig']
#
#twig:
#  debug:            "%kernel.debug%"
#  strict_variables: "%kernel.debug%"
#  paths:
#    "%kernel.root_dir%/../src/Usac/Api/Resources/views/la": landingpage