imports:
    - { resource: config.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

parameters:
    database_driver: pdo_sqlite
    database_path: %kernel.cache_dir%/test.db

