#framework:
#  validation:
#    cache: apc

#doctrine:
#  orm:
#    metadata_cache_driver: apc
#    result_cache_driver: apc
#    query_cache_driver: apc

parameters:
    php_commerce.root_dir: %kernel.root_dir%/..


