#framework:
#  validation:
#    cache: apc

#doctrine:
#  orm:
#    metadata_cache_driver: apc
#    result_cache_driver: apc
#    query_cache_driver: apc

framework:
    router: { resource: "%php_commerce.root_dir%/src/PHPCommerce/Bundle/Resources/config/routing.yml" }

parameters:
    php_commerce.root_dir: %kernel.root_dir%/..


