#framework:
#  validation:
#    cache: apc

#doctrine:
#  orm:
#    metadata_cache_driver: apc
#    result_cache_driver: apc
#    query_cache_driver: apc

framework:
    router: { resource: "%php_commerce.root_dir%/src/PHPCommerce/Bundle/Resources/config/routing.yml" }

parameters:
    php_commerce.root_dir: %kernel.root_dir%/..

    php_commerce.database.driver: pdo_mysql
    php_commerce.database.host: 127.0.0.1
    php_commerce.database.port: 3306
    php_commerce.database.name: phpcommerce
    php_commerce.database.user: root
    php_commerce.database.password: