parameters:
    phpcommerce.root_dir: %kernel.root_dir%/../vendor/phpcommerce/phpcommerce

imports:
    - { resource: parameters.yml }
    - { resource: "bundles/framework.yml" }
    - { resource: "bundles/twig.yml" }
    - { resource: "bundles/doctrine.yml" }
    - { resource: "bundles/doctrine_migrations.yml" }
    - { resource: "bundles/doctrine_orm.yml" }
    - { resource: "bundles/doctrine_cache.yml" }

    - { resource: "../../../Common/Resources/config/config.yml" }
    - { resource: "../../../Payment/Resources/config/config.yml" }
    - { resource: "../../../ERP/Resources/config/config.yml" }

framework:
    router: { resource: "%phpcommerce.root_dir%/src/PHPCommerce/Bundle/Resources/config/routing.yml" }

