framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

parameters:
    phpcommerce.root_dir: %kernel.root_dir%/..
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: phpcommerce
    database_user: root
    database_password:
    database_path: null
