imports:
    - { resource: config_standalone_dev.yml }

parameters:
    php_commerce.root_dir: %kernel.root_dir%/..

    php_commerce.database.driver: pdo_sqlite
    php_commerce.database.path: %kernel.cache_dir%/test.db

