doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db

    orm:
        mappings:
            ERP:
                type: yml
                is_bundle: false
                prefix: PHPCommerce\ERP\Entity
                dir: %kernel.root_dir%/../src/PHPCommerce/ERP/Resources/config/doctrine

            Payment:
                type: yml
                is_bundle: false
                prefix: PHPCommerce\Payment\Entity
                dir: %kernel.root_dir%/../src/PHPCommerce/Payment/Resources/config/doctrine