parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony
    database_user: root
    database_password: root
    database_path: null

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    log_level: error

    locale: en
    secret: 6b9cb4012fb0a383b5400c5380e764505e206502
