parameters:
    php_commerce.root_dir: %kernel.root_dir%/../vendor/phpcommerce/phpcommerce

    php_commerce.secret: 59cd82f0783aa6f05cf3324b13d008d8747c6576


    php_commerce.database.driver:
    php_commerce.database.host:
    php_commerce.database.port:
    php_commerce.database.name:
    php_commerce.database.user:
    php_commerce.database.password:
    php_commerce.database.path:

#    mailer_transport: smtp
#    mailer_host: 127.0.0.1
#    mailer_user: null
#    mailer_password: null

#    log_level: error

#    locale: en
