ERP:
    resource: "../../../ERP/Resources/config/routing.yml"

Payment:
    resource: "../../../Payment/Resources/config/routing.yml"

Shop:
    resource: "../../../Shop/Resources/config/routing.yml"

