doctrine:
  orm:
    entity_managers:
      default:
        mappings:
          ERP:
            mapping: true
            type: yml
            dir: %kernel.root_dir%/../src/PHPCommerce/Common/Resources/config/doctrine
            is_bundle: false
            prefix: PHPCommerce\Common
