doctrine:
  orm:
    entity_managers:
      default:
        mappings:
          Common:
            mapping: true
            type: yml
            dir: %phpcommerce.root_dir%/src/PHPCommerce/Common/Resources/config/doctrine
            is_bundle: false
            prefix: PHPCommerce\Common\Entity
